version: '3'

services:
  scoring-nginx: # 服务名称
    container_name: scoring-nginx
    image: fya392/scoring-nginx:1.2
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # 挂载 conf 文件
    privileged: true # 解决 nginx 的文件调用权限
  mysql:
    container_name: scoring-mysql
    image: mysql:latest
    volumes:
      - ./mysql/:/var/lib/mysql/
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  redis:
    container_name: scoring-redis
    image: redis:latest

  tomcat:
    container_name: scoring-tomcat
    image: tomcat:8.5.70
    ports:
      - 8080:8080
    volumes:
      - ./war/:/usr/local/tomcat/webapps # 放 war 包
    depends_on:
      - mysql
      - redis
