version: '3'

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1



volumes:
  grafana_data: {}


services:
  scoring-nginx: # 服务名称
    container_name: scoring-nginx
    image: nginx
    ports:
      - 81:81
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # 挂载 conf 文件
      - ./html:/usr/share/nginx/html
    privileged: true # 解决 nginx 的文件调用权限
    networks:
      mynetwork:
        ipv4_address: 172.19.0.2

  mysql:
    container_name: scoring-mysql
    image: mysql:latest
    volumes:
      - ./mysql/:/var/lib/mysql/
    ports:
      - "3005:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      mynetwork:
        ipv4_address: 172.19.0.3

  redis:
    container_name: scoring-redis
    image: redis:latest
    networks:
      mynetwork:
        ipv4_address: 172.19.0.4

  tomcat:
    container_name: scoring-tomcat
    image: tomcat:8.5.70
    ports:
      - 3004:8080
    volumes:
      - ./war/:/usr/local/tomcat/webapps # 放 war 包
      - ./tomcatlog/:/usr/local/tomcat/logs
    depends_on:
      - mysql
      - redis
    networks:
      mynetwork:
        ipv4_address: 172.19.0.5


  influxdb:
    image: tutum/influxdb:0.9
    restart: always
    environment:
      - PRE_CREATE_DB=cadvisor
    ports:
      - "3003:8083"
      - "3002:8086"
    volumes:
      - ./data/influxdb:/data

  cadvisor:
    image: google/cadvisor
    links:
      - influxdb:influxsrv
    command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxsrv:8086
    restart: always
    privileged: true
    ports:
      - "3001:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  grafana:
    user: "104"
    image: grafana/grafana
    restart: always
    links:
      - influxdb:influxsrv
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - HTTP_USER=admin
      - HTTP_PASS=admin
      - INFLUXDB_HOST=influxsrv
      - INFLUXDB_PORT=8086
      - INFLUXDB_NAME=cadvisor
      - INFLUXDB_USER=root
      - INFLUXDB_PASS=root


  mysqlexporter:
    image: prom/mysqld-exporter
    ports:
      - "9104:9104"
    environment:
      - DATA_SOURCE_NAME=root:123456@(mysql:3306)/mark
    networks:
      mynetwork:
        ipv4_address: 172.19.0.5


  prometheus:
    image: bitnami/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus_data:/prometheus
    user: root
    privileged: true
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always